networks:
  docker-network:
    name: docker-network
    external: true

services:
  tw-analytics-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tw-analytics-api
    # 开发环境暴露端口到主机
    ports:
      - "${PORT:-5100}:5100"
    env_file:
      - ../.env
    volumes:
      - "${PWD}/instance:/app/instance:rw"  # 挂载实例目录（已移除cookie系统）
      - "${PWD}/src/config/accounts.json:/app/src/config/accounts.json:ro"  # 挂载账户配置文件（只读）
    # user: "1000:1000"  # Dockerfile中已配置app用户，无需覆盖
    environment:
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      # 账户配置已迁移到统一账户管理系统
      # - TWITTER_USERNAME=${TWITTER_USERNAME}  # 已迁移到src/config/accounts.json
      # - TWITTER_PASSWORD=${TWITTER_PASSWORD}  # 已迁移到src/config/accounts.json
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY:-production-secret-key}
      - HOST=0.0.0.0
      - PORT=5100
      - PLAYWRIGHT_HEADLESS=true
      - PLAYWRIGHT_PROXY=${PLAYWRIGHT_PROXY:-}
      - MAX_TWEETS_PER_REQUEST=${MAX_TWEETS_PER_REQUEST:-100}
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE:-50}
      - DEFAULT_TWEET_COUNT=${DEFAULT_TWEET_COUNT:-10}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - docker-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5100/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s