# TW Analytics API Docker Compose Configuration Example
version: '3.8'

services:
  tw-analytics:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: tw-analytics
    ports:
      - "5100:5100"
    volumes:
      - ../instance:/app/instance
      - ../src/config/accounts.json:/app/src/config/accounts.json:ro  # 挂载账户配置文件（只读）
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app/src
      - HOST=0.0.0.0
      - PORT=5100
      # Twitter Configuration - Replace with your actual credentials
      - TWITTER_BEARER_TOKEN=your_bearer_token_here
      # 账户配置已迁移到统一账户管理系统 (src/config/accounts.json)
      # - TWITTER_USERNAME=your_username_here  # 已迁移到accounts.json
      # - TWITTER_PASSWORD=your_password_here  # 已迁移到accounts.json
      # - TWITTER_EMAIL=your_email_here        # 已迁移到accounts.json
      - PLAYWRIGHT_HEADLESS=true
      # - COOKIE_FILE_PATH=instance/twitter_cookies.json  # 已移除cookie系统
      # Flask Configuration
      - SECRET_KEY=your-secret-key-here
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5100/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# Usage Instructions:
# 1. Copy this file to docker-compose.yml
# 2. Configure accounts in src/config/accounts.json (see accounts.json.example)
# 3. Replace TWITTER_BEARER_TOKEN with your actual token
# 4. Run: docker-compose up -d
# 5. Access API at: http://localhost:5100